# Assignment 1 - All About torch.Tensor

### Deep Learning with PyTorch: Zero to GANs

An short introduction about PyTorch and about the chosen functions. 
- Tensors size
- Casting functions
- Element-wise arithmetic functions
- Example of in-place functions
- Inverse function

In [40]:
# Import torch and other required modules
import torch

## Function 1 - Tensors size

Everytime we are using a tensor, we must be aware and cautious about tensor size. It leads very often to errors and can be tricky to debug. Getting a tensor size is the starting point.  
The function **size()** (equivalent to **.shape**) is used in the following examples.

Tensor a

In [20]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(a.size())
assert a.size()==a.shape

torch.Size([3, 2])


Tensor b

In [21]:
b = torch.tensor([[1, 2]])
b.size()

torch.Size([1, 2])

We now try to run matrix multiplication between tensor a and b.

In [22]:
a @ b

RuntimeError: size mismatch, m1: [3 x 2], m2: [1 x 2] at /opt/conda/conda-bld/pytorch_1587428266983/work/aten/src/TH/generic/THTensorMath.cpp:41

We got an error regarding "size mismatch". If we look back at the sizes, we realize it is necessary to transpose b to be able to do matric multiplication.

In [24]:
a @ b.T

tensor([[ 5],
        [11],
        [17]])

When developing a Deep Learning algorithm or any algorithm actually, being careful about size is essential.  

To go further and change a tensor shape, the functions **view** or **reshape** should be used :
- Tensor.view() works only on contiguous tensors and will never copy memory. It will raise an error on a non-contiguous tensor.
- Tensor.reshape() will work on any tensor and can make a clone if it is needed.

## Function 2 - Casting functions

In many case, it is important to know the type of data we have in tensors (float, int...).  
There are different ways to cast a tensor:
- **to(dtype)**
- **type(dtype)**
- **type_as(tensor)**
- specific functions for each target type: **float()**, **double()**, **int()**...

The tensor type can be found using the function type() without any parameter.

We start with a tensor *t_int* containing integer elements.

In [25]:
t_int = torch.tensor([[1, 2], [3, 4]])
t_int.type()

'torch.LongTensor'

We will now present different ways to cast this tensor into float type.

Function **to(dtype)**

In [26]:
t_flt = t_int.to(torch.float32)
t_flt.type()

'torch.FloatTensor'

Function **type(dtype)**

In [7]:
t_flt = t_int.type("torch.FloatTensor")
t_flt.type()

'torch.FloatTensor'

Function **float()**

In [8]:
t_flt = t_int.float()
t_flt.type()

'torch.FloatTensor'

Function **type_as(tensor)**

In [27]:
t_flt_temp = t_int.float()
t_flt = t_int.type_as(t_flt_temp)
t_flt.type()

'torch.FloatTensor'

Tensor type is very important because it can lead to errors (as we will see in **Function 3 - Arithmetic functions**.   
Pytorch provides many different solutions to cast a tensor to another type.

## Function 3 - Arithmetic functions

Pytorch library contains a bunch of built-in arithmetic functions.  
When calling these functions on a tensor, it will apply the transformation element-wise.

Below are examples of the use of **sqrt** and **cos** functions.

Initialization of two tensors

In [41]:
a = torch.tensor([[1., 2], [-3, 4], [0, 6]])
b = torch.tensor([[1, 2]])

Root-square function applied to **a** and **b** tensors

In [42]:
print(a.type())
a.sqrt()

torch.FloatTensor


tensor([[1.0000, 1.4142],
        [   nan, 2.0000],
        [0.0000, 2.4495]])

When the function is not applicable (e.g negative value for square-root), the value is set to nan.

In [43]:
print(b.type())
b.sqrt()

torch.LongTensor


RuntimeError: sqrt_vml_cpu not implemented for 'Long'

If we now cast the tensor b into a FloatTensor, the function is working.

In [45]:
b_temp = b.float()
print(b_temp.type())
b_temp.sqrt()

torch.FloatTensor


tensor([[1.0000, 1.4142]])

Cosinus function applied to **a** and **b** tensors

In [15]:
print(a.type())
a.cos()

torch.FloatTensor


tensor([[ 0.5403, -0.4161],
        [-0.9900, -0.6536],
        [ 1.0000,  0.9602]])

In [16]:
print(b.type())
b.cos()

torch.LongTensor


RuntimeError: cos_vml_cpu not implemented for 'Long'

If we now cast the tensor b into a FloatTensor, the function is working.

In [29]:
b_temp = b.float()
print(b_temp.type())
b_temp.cos()

torch.FloatTensor


tensor([[ 0.5403, -0.4161]])

We observe that the two functions only work with float tensors.  
We must be careful about tensor types when calling arithmetic functions and eventually apply functions to cast them (as we have seen in the previous part), to be able to run the functions.

## Function 4 - Example of an in-place function

**tensor.log** function computes the natural logarithm of each element of the tensor.  
**tensor.log_** is the "*in_place*" version of **tensor.log**, we will now see what it means on concrete examples.

After initializing a tensor t, we call **t.log()** function.  
If we print t afterward, we observe that t values did not change.

In [46]:
t = torch.tensor([[1., 2.], [3., 4.]])
print(t.log())
print(t)

tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])
tensor([[1., 2.],
        [3., 4.]])


If we run the exact same lines of code but using **t.log_()**, we now see that the values of the tensor t are the logarithm of its elements.  
The inital values of t have been replaced, it is how "*in-place*" functions are working. 

In [47]:
t = torch.tensor([[1., 2.], [3., 4.]])
print(t.log_())
print(t)

tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])
tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])


If we store the results of functions **log()** and **log_()** in temporary tensors, we obtain the same results for both functions.

In [48]:
t = torch.tensor([[1., 2.], [3., 4.]])
t1 = t.log()
t2 = t.log_()
print(t1)
print(t2)

tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])
tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])


## Function 4 - Inverse function

**tensor.inverse** function computes the inverse of the square matrix.  

The results of the function is the inverse of t that is a [2, 2] tensor.

In [49]:
t = torch.tensor([[1., 2], [3, 4]])
print(t.size())
t.inverse() 

torch.Size([2, 2])


tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

The function is not working with int tensors.

In [50]:
t = torch.tensor([[1, 2], [3, 4]])
print(t.type())
t.inverse() 

torch.LongTensor


RuntimeError: "inverse_cpu" not implemented for 'Long'

It is only possible to inverse square matrices (n=m). In this case, it is a [3,2] matrix so an error is raised.

In [51]:
t = torch.tensor([[1., 2], [3, 4], [5, 6]])
print(t.size())
t.inverse() 

torch.Size([3, 2])


RuntimeError: A must be batches of square matrices, but they are 2 by 3 matrices

## Conclusion

When using tensors and associated functions, **size** and **types** are essential. Checking for them while developing should be a reflex, it could save a lot of debugging time.  

Then, some built-in functions was presented, either matrix operations or element-wise arithmetic functions.  
In both cases, we faced errors regarding types and size! 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* Pytorch forum : https://discuss.pytorch.org/t/in-pytorch-0-4-is-it-recommended-to-use-reshape-than-view-when-it-is-possible/17034

In [52]:
!pip install jovian --upgrade --quiet

In [53]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
